import type { ChargingStation, Route, BikeRepairStation } from '../types/navigation';

/**
 * Curated High-Quality E-Bike Infrastructure Database
 * Verified charging stations across DACH regions (Berlin, Brandenburg, Bayern, Bodensee, Schwarzwald, Rheinland, Nordseeküste, Harz)
 */
export const CURATED_CHARGING_STATIONS: ChargingStation[] = [
  // 1. Berlin & Brandenburg
  {
    id: 'cs-berlin-01',
    name: 'E-Bike Tankstelle Café Badesee Müggelsee',
    lat: 52.4485,
    lng: 13.6280,
    plugType: 'bosch',
    isWeatherproof: true,
    isFree: true,
    openingHours: '08:00 - 21:00',
    nearbyAmenities: ['Café', 'Sitzbänke', 'WLAN', 'Fahrradständer', 'Badesee'],
    photoUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=500',
    verifiedByCount: 38,
    createdAt: '2026-06-15T10:00:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },
  {
    id: 'cs-berlin-02',
    name: 'Öffentlicher 230V Schuko Lade-Locker Alexanderplatz',
    lat: 52.5218,
    lng: 13.4132,
    plugType: 'schuko_230v',
    isWeatherproof: true,
    isFree: true,
    openingHours: '24/7',
    nearbyAmenities: ['Luftpumpe', 'Werkzeugstation', 'ÖPNV-Anschluss'],
    photoUrl: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=500',
    verifiedByCount: 45,
    createdAt: '2026-06-18T12:00:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },
  {
    id: 'cs-berlin-03',
    name: 'BikeEnergy Schnellladestation Wannsee Terrassen',
    lat: 52.4242,
    lng: 13.1785,
    plugType: 'bike_energy',
    isWeatherproof: true,
    isFree: false,
    openingHours: '09:00 - 22:00',
    nearbyAmenities: ['Restaurant', 'WC', 'Werkzeug', 'Seeblick'],
    verifiedByCount: 52,
    createdAt: '2026-06-20T14:30:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },
  {
    id: 'cs-potsdam-01',
    name: 'E-Bike Ladepunkt Schloss Cecilienhof',
    lat: 52.4195,
    lng: 13.0712,
    plugType: 'schuko_230v',
    isWeatherproof: true,
    isFree: true,
    openingHours: '24/7',
    nearbyAmenities: ['Museum', 'Schlosspark', 'Trinkwasser'],
    verifiedByCount: 29,
    createdAt: '2026-07-01T09:15:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },
  {
    id: 'cs-spreewald-01',
    name: 'Spreewald Solar-Ladestation Lübbenau Hafen',
    lat: 51.8688,
    lng: 13.9665,
    plugType: 'bosch',
    isWeatherproof: true,
    isFree: true,
    openingHours: '07:00 - 20:00',
    nearbyAmenities: ['Kahnhafen', 'Gastronomie', 'Fahrradverleih'],
    verifiedByCount: 34,
    createdAt: '2026-07-04T11:00:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },

  // 2. Bayern & Alpen-Region
  {
    id: 'cs-munich-01',
    name: 'Isarradweg E-Bike Hub Aumeister Biergarten',
    lat: 51.1845,
    lng: 11.6210,
    plugType: 'schuko_230v',
    isWeatherproof: true,
    isFree: true,
    openingHours: '10:00 - 23:00',
    nearbyAmenities: ['Biergarten', 'Bierbank-Ladeboxen', 'Werkzeug'],
    verifiedByCount: 67,
    createdAt: '2026-07-08T15:00:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },
  {
    id: 'cs-tegernsee-01',
    name: 'Tegernsee Panorama Bike-Energy Schnelllader',
    lat: 47.7082,
    lng: 11.7565,
    plugType: 'bike_energy',
    isWeatherproof: true,
    isFree: false,
    openingHours: '24/7',
    nearbyAmenities: ['Uferpromenade', 'Café', 'Akku-Schließfächer'],
    verifiedByCount: 81,
    createdAt: '2026-07-10T08:30:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },
  {
    id: 'cs-garmisch-01',
    name: 'Zugspitz-Blick E-Bike Station Eibsee',
    lat: 47.4562,
    lng: 10.9928,
    plugType: 'bosch',
    isWeatherproof: true,
    isFree: true,
    openingHours: '08:00 - 19:00',
    nearbyAmenities: ['Bergbahn', 'Restaurant', 'Schlauchautomat'],
    verifiedByCount: 94,
    createdAt: '2026-07-12T13:45:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },

  // 3. Bodensee & Schwarzwald
  {
    id: 'cs-bodensee-01',
    name: 'Bodensee-Radweg PowerStation Lindau Insel',
    lat: 47.5458,
    lng: 9.6835,
    plugType: 'schuko_230v',
    isWeatherproof: true,
    isFree: true,
    openingHours: '24/7',
    nearbyAmenities: ['Hafen', 'Tourismus-Info', 'Reparaturstation'],
    verifiedByCount: 112,
    createdAt: '2026-07-14T16:20:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },
  {
    id: 'cs-schwarzwald-01',
    name: 'Schwarzwald Höhen-Ladestation Titisee Seestraße',
    lat: 47.9015,
    lng: 8.1528,
    plugType: 'bosch',
    isWeatherproof: true,
    isFree: true,
    openingHours: '08:00 - 21:00',
    nearbyAmenities: ['See-Promenade', 'Kiosk', 'Fahrradwerkstatt'],
    verifiedByCount: 76,
    createdAt: '2026-07-16T10:10:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },

  // 4. Rheinland & Mosel
  {
    id: 'cs-koeln-01',
    name: 'Rheinradweg Köln Deutzer Rheinufer E-Locker',
    lat: 50.9380,
    lng: 6.9690,
    plugType: 'schuko_230v',
    isWeatherproof: true,
    isFree: true,
    openingHours: '24/7',
    nearbyAmenities: ['Rheinblick', 'Gastronomie', 'Fahrradstraße'],
    verifiedByCount: 58,
    createdAt: '2026-07-18T14:00:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },
  {
    id: 'cs-mosel-01',
    name: 'Moselradweg Weinstation Cochem Promenade',
    lat: 50.1465,
    lng: 7.1680,
    plugType: 'bike_energy',
    isWeatherproof: true,
    isFree: false,
    openingHours: '09:00 - 22:00',
    nearbyAmenities: ['Weinstube', 'Sonnenterrasse', 'E-Bike Verleih'],
    verifiedByCount: 88,
    createdAt: '2026-07-20T11:30:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },

  // 5. Norddeutschland & Ostseeküste
  {
    id: 'cs-hamburg-01',
    name: 'Elberadweg Landungsbrücken Hamburg Bike-Hub',
    lat: 53.5455,
    lng: 9.9675,
    plugType: 'schuko_230v',
    isWeatherproof: true,
    isFree: true,
    openingHours: '24/7',
    nearbyAmenities: ['Fähren', 'Fischbrötchen', 'Werkzeug'],
    verifiedByCount: 63,
    createdAt: '2026-07-22T09:00:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },
  {
    id: 'cs-ruegen-01',
    name: 'Ostseeküsten-Radweg Binz Seebrücke Schnelllader',
    lat: 54.4010,
    lng: 13.6120,
    plugType: 'bosch',
    isWeatherproof: true,
    isFree: true,
    openingHours: '24/7',
    nearbyAmenities: ['Strandpromenade', 'Kurpark', 'WLAN'],
    verifiedByCount: 71,
    createdAt: '2026-07-24T12:15:00Z',
    createdByUserId: 'system_curated',
    isVerifiedBikeInfrastructure: true,
  },
];

/**
 * Public 24/7 Bike Repair Stations & Tube Vending Pillars
 */
export const CURATED_REPAIR_STATIONS: BikeRepairStation[] = [
  {
    id: 'rep-berlin-01',
    name: 'ADFC Fahrrad-Servicestation Brandenburger Tor',
    lat: 52.5163,
    lng: 13.3777,
    hasAirPump: true,
    hasTools: true,
    hasTubeVending: true,
  },
  {
    id: 'rep-berlin-02',
    name: 'Schwalbe Schlauchautomat & Standpumpe Tempelhofer Feld',
    lat: 52.4735,
    lng: 13.4020,
    hasAirPump: true,
    hasTools: true,
    hasTubeVending: true,
  },
  {
    id: 'rep-potsdam-01',
    name: 'BikeRepair Point Potsdam Luisenplatz',
    lat: 52.3995,
    lng: 13.0480,
    hasAirPump: true,
    hasTools: true,
    hasTubeVending: false,
  },
  {
    id: 'rep-munich-01',
    name: 'Stadt München E-Bike Reparatur-Säule Marienplatz',
    lat: 48.1374,
    lng: 11.5755,
    hasAirPump: true,
    hasTools: true,
    hasTubeVending: true,
  },
];

/**
 * Curated Top E-Bike Routes in Germany with real terrain & waypoints
 */
export const CURATED_ROUTES: Route[] = [
  {
    id: 'route-mueggelsee-loop',
    title: 'Müggelsee & Rahnsdorf E-Bike Loop',
    summary: 'Malerische Seenroute mit flachen Asphaltwegen, Waldpassagen und 2 zertifizierten Ladestationen.',
    aiStory: 'Entspannte Tour entlang des Müggelsees mit Zwischenstopp im Biergarten Rübezahl und Strandbad Rahnsdorf.',
    distanceKm: 34.2,
    elevationGainM: 110,
    estimatedTimeMin: 85,
    estimatedBatteryConsumptionWh: 145,
    isBatterySafe: true,
    surfaceBreakdown: { asphaltPercent: 80, gravelPercent: 15, unpavedPercent: 5 },
    waypoints: [
      { id: 'wp-1', lat: 52.450, lng: 13.620, name: 'Start Müggelsee Park', category: 'start' },
      { id: 'wp-2', lat: 52.430, lng: 13.680, name: 'Rahnsdorf Strandbad', category: 'scenic' },
      { id: 'wp-3', lat: 52.448, lng: 13.628, name: 'E-Bike Tankstelle Café Badesee', category: 'charging' },
      { id: 'wp-4', lat: 52.455, lng: 13.610, name: 'Friedrichshagen Marktplatz', category: 'end' },
    ],
    pathCoordinates: [
      [52.520, 13.405],
      [52.510, 13.430],
      [52.480, 13.520],
      [52.450, 13.620],
      [52.430, 13.680],
      [52.448, 13.628],
      [52.455, 13.610],
    ],
    chargingStopsOnRoute: [],
  },
  {
    id: 'route-potsdam-lakes',
    title: 'Potsdamer Schlösser & Havelseen Promenade',
    summary: 'Kulturelle Radtour vorbei an Schloss Sanssouci, Neuem Garten und Templiner See.',
    aiStory: 'Exklusive Tour mit herrschaftlichen Ausblicken, ruhigen Uferwegen und perfektem Radwegbelag.',
    distanceKm: 28.5,
    elevationGainM: 95,
    estimatedTimeMin: 70,
    estimatedBatteryConsumptionWh: 120,
    isBatterySafe: true,
    surfaceBreakdown: { asphaltPercent: 90, gravelPercent: 10, unpavedPercent: 0 },
    waypoints: [
      { id: 'wp-p1', lat: 52.395, lng: 13.065, name: 'Potsdam Hauptbahnhof', category: 'start' },
      { id: 'wp-p2', lat: 52.404, lng: 13.038, name: 'Schloss Sanssouci', category: 'scenic' },
      { id: 'wp-p3', lat: 52.419, lng: 13.071, name: 'E-Bike Ladepunkt Schloss Cecilienhof', category: 'charging' },
      { id: 'wp-p4', lat: 52.410, lng: 13.085, name: 'Glienicker Brücke', category: 'end' },
    ],
    pathCoordinates: [
      [52.395, 13.065],
      [52.404, 13.038],
      [52.415, 13.055],
      [52.419, 13.071],
      [52.410, 13.085],
    ],
    chargingStopsOnRoute: [],
  },
  {
    id: 'route-tegernsee-panoramatour',
    title: 'Tegernsee & Schliersee Voralpen-Runde',
    summary: 'Traumhafte Voralpen-Tour mit 340 Höhenmetern, Bergpanorama und Schnellladestationen.',
    aiStory: 'Sportliche E-Bike Tour mit gemäßigten Anstiegen, Bergpanoramablick und bayerischer Einkehr.',
    distanceKm: 42.0,
    elevationGainM: 340,
    estimatedTimeMin: 110,
    estimatedBatteryConsumptionWh: 260,
    isBatterySafe: true,
    surfaceBreakdown: { asphaltPercent: 75, gravelPercent: 25, unpavedPercent: 0 },
    waypoints: [
      { id: 'wp-t1', lat: 47.712, lng: 11.758, name: 'Tegernsee Bahnhof', category: 'start' },
      { id: 'wp-t2', lat: 47.695, lng: 11.782, name: 'Rottach-Egern Uferpromenade', category: 'scenic' },
      { id: 'wp-t3', lat: 47.708, lng: 11.756, name: 'Tegernsee Panorama Bike-Energy Schnelllader', category: 'charging' },
      { id: 'wp-t4', lat: 47.735, lng: 11.820, name: 'Schliersee Kurpark', category: 'end' },
    ],
    pathCoordinates: [
      [47.712, 11.758],
      [47.695, 11.782],
      [47.708, 11.756],
      [47.735, 11.820],
    ],
    chargingStopsOnRoute: [],
  },
  {
    id: 'route-bodensee-lindau-bregenz',
    title: 'Bodensee Ufer-Tour Lindau bis Meersburg',
    summary: 'Flache Panoramafahrt entlang des Bodenseeufers mit Obstgärten und Blick auf die Schweizer Alpen.',
    aiStory: 'Der Klassiker unter den E-Bike Strecken: 100% flach, durchgehend asphaltiert und optimal ausgeschildert.',
    distanceKm: 48.6,
    elevationGainM: 85,
    estimatedTimeMin: 125,
    estimatedBatteryConsumptionWh: 195,
    isBatterySafe: true,
    surfaceBreakdown: { asphaltPercent: 95, gravelPercent: 5, unpavedPercent: 0 },
    waypoints: [
      { id: 'wp-b1', lat: 47.545, lng: 9.683, name: 'Lindau Insel Hafen', category: 'start' },
      { id: 'wp-b2', lat: 47.575, lng: 9.590, name: 'Wasserburg Schloss Halbinsel', category: 'scenic' },
      { id: 'wp-b3', lat: 47.652, lng: 9.475, name: 'Friedrichshafen Schlosskirche', category: 'charging' },
      { id: 'wp-b4', lat: 47.695, lng: 9.270, name: 'Meersburg Schlossplatz', category: 'end' },
    ],
    pathCoordinates: [
      [47.545, 9.683],
      [47.575, 9.590],
      [47.652, 9.475],
      [47.695, 9.270],
    ],
    chargingStopsOnRoute: [],
  },
  {
    id: 'route-spreewald-gurkenradweg',
    title: 'Spreewald Gurkenradweg Kahn-Romantik',
    summary: 'Radeln entlang der Fließe und Kanäle des UNESCO-Biosphärenreservats Spreewald.',
    aiStory: 'Idyllische Naturstrecke auf befestigten Wegen mit traditionellen Fischerdörfern und schattigen Erlenwäldern.',
    distanceKm: 38.4,
    elevationGainM: 45,
    estimatedTimeMin: 95,
    estimatedBatteryConsumptionWh: 135,
    isBatterySafe: true,
    surfaceBreakdown: { asphaltPercent: 85, gravelPercent: 15, unpavedPercent: 0 },
    waypoints: [
      { id: 'wp-s1', lat: 51.868, lng: 13.966, name: 'Lübbenau Grosser Hafen', category: 'start' },
      { id: 'wp-s2', lat: 51.872, lng: 14.015, name: 'Lehde Freilandmuseum', category: 'scenic' },
      { id: 'wp-s3', lat: 51.868, lng: 13.966, name: 'Spreewald Solar-Ladestation', category: 'charging' },
      { id: 'wp-s4', lat: 51.895, lng: 13.920, name: 'Lübben Schlossinsel', category: 'end' },
    ],
    pathCoordinates: [
      [51.868, 13.966],
      [51.872, 14.015],
      [51.895, 13.920],
    ],
    chargingStopsOnRoute: [],
  },
];
